version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3003:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=leara
      - POSTGRES_PASSWORD=Rumisir505
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leara -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_api:/var/lib/postgresql/data

volumes:
  db_api:
    external: true
